-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
date_format(B.CREATED_DATE , '%Y-%m-%d')
from USED_GOODS_BOARD A,
    USED_GOODS_REPLY B
where date_format(A.CREATED_DATE, '%Y-%m') = '2022-10'
AND A.BOARD_ID = B.BOARD_ID
order by B.CREATED_DATE ASC, A.title ASC